- project:
    check: &jobs
      jobs:
        - cabal-test:
            vars:
              ghc_version: 8.8
            nodeset:
              nodes:
                - name: container
                  label: zuul-worker-haskell
        - hlint:
            nodeset:
              nodes:
                - name: container
                  label: pod-haskell-f32
    gate: *jobs
